RMS_MVC/Controllers/ServiceOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMS_MVC.Models;

namespace RMS_MVC.Controllers
{
    [Authorize]
    public class ServiceOrderController : Controller
    {
        private RmsContext db = new RmsContext();

        //
        // GET: /ServiceOrder/

        public ActionResult Index()
        {
            var serviceorders = db.ServiceOrders.Include(s => s.Client);
            return View(serviceorders.ToList());
        }

        //
        // GET: /ServiceOrder/Details/5

        public ActionResult Details(int id = 0)
        {
            ServiceOrder serviceorder = db.ServiceOrders.Find(id);
            if (serviceorder == null)
            {
                return HttpNotFound();
            }
            return View(serviceorder);
        }

        //
        // GET: /ServiceOrder/Create

        public ActionResult Create()
        {
            ViewBag.ClientID = new SelectList(db.Clients, "ClientID", "LastName");
            return View();
        }

        //
        // POST: /ServiceOrder/Create

        [HttpPost]
        public ActionResult Create(ServiceOrder serviceorder)
        {
            if (ModelState.IsValid)
            {
                db.ServiceOrders.Add(serviceorder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientID = new SelectList(db.Clients, "ClientID", "LastName", serviceorder.ClientID);
            return View(serviceorder);
        }

        //
        // GET: /ServiceOrder/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ServiceOrder serviceorder = db.ServiceOrders.Find(id);
            if (serviceorder == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientID = new SelectList(db.Clients, "ClientID", "LastName", serviceorder.ClientID);
            return View(serviceorder);
        }

        //
        // POST: /ServiceOrder/Edit/5

        [HttpPost]
        public ActionResult Edit(ServiceOrder serviceorder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceorder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClientID = new SelectList(db.Clients, "ClientID", "LastName", serviceorder.ClientID);
            return View(serviceorder);
        }

        //
        // GET: /ServiceOrder/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ServiceOrder serviceorder = db.ServiceOrders.Find(id);
            if (serviceorder == null)
            {
                return HttpNotFound();
            }
            return View(serviceorder);
        }

        //
        // POST: /ServiceOrder/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceOrder serviceorder = db.ServiceOrders.Find(id);
            db.ServiceOrders.Remove(serviceorder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RMS_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - RMS</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Repair Management System", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Client", "Index", "Client")</li>
                            <li>@Html.ActionLink("Service Order", "Index", "ServiceOrder")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Repair Management System</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>